export const APPLICATION_ERROR_CODES = {
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export const DOMAIN_ERROR_CODES = {
  DATABASE_ERROR: 'DATABASE_ERROR',
  NEGATIVE_BALANCE: 'NEGATIVE_BALANCE',
  EMPTY_PASSWORD: 'EMPTY_PASSWORD',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_ACCOUNT_NAME: 'INVALID_ACCOUNT_NAME',
  EMPTY_WALLET_NAME: 'EMPTY_WALLET_NAME',
  WALLET_NAME_EXCEED_MAX_LENGTH: 'WALLET_NAME_EXCEED_MAX_LENGTH',
  ACCOUNT_NAME_EXCEED_MAX_LENGTH: 'ACCOUNT_NAME_EXCEED_MAX_LENGTH',
} as const;

export const ERROR_CODES = {
  ...APPLICATION_ERROR_CODES,
  ...DOMAIN_ERROR_CODES,
} as const;

