export const AUTH_PREFIX = 'auth' as const;

export const AUTH_ACTION_TYPES = {
  LOGIN_USER: `${AUTH_PREFIX}/loginUser`,
  REGISTER_USER: `${AUTH_PREFIX}/registerUser`,
} as const;

export const AUTH_ACTION_TYPES_FULL = {
  LOGIN_USER_PENDING: `${AUTH_ACTION_TYPES.LOGIN_USER}/pending`,
  LOGIN_USER_FULFILLED: `${AUTH_ACTION_TYPES.LOGIN_USER}/fulfilled`,
  LOGIN_USER_REJECTED: `${AUTH_ACTION_TYPES.LOGIN_USER}/rejected`,
  REGISTER_USER_PENDING: `${AUTH_ACTION_TYPES.REGISTER_USER}/pending`,
  REGISTER_USER_FULFILLED: `${AUTH_ACTION_TYPES.REGISTER_USER}/fulfilled`,
  REGISTER_USER_REJECTED: `${AUTH_ACTION_TYPES.REGISTER_USER}/rejected`,
} as const;

